## Types of data
1) Qualitative - Nominal and Ordinal
2) Quantiative - Discrete, Continuous
3) Structured Data, Unstructured Data

# Numpy - Numerical Python

In [3]:
pip install numpy

Note: you may need to restart the kernel to use updated packages.


In [4]:
import numpy as np

In [5]:
#Zero Dimensional array
a = np.array(42)
a

array(42)

In [6]:
#One Dimensional array
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [7]:
#Two Dimsensional array
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [8]:
#Three Dimensional array
a = np.array([[[1, 2, 3], [4, 5, 6] , [7, 8, 9]]])
a

array([[[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]])

In [9]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [10]:
print(a.shape)

(5,)


In [11]:
b = a.reshape(5, 1)
b

array([[1],
       [2],
       [3],
       [4],
       [5]])

In [12]:
#arange():
np.arange(0, 10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [13]:
np.arange(0, 10, 2)

array([0, 2, 4, 6, 8])

In [14]:
#ones
np.ones(3)

array([1., 1., 1.])

In [15]:
np.ones((3, 4))

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [16]:
#zeros
np.zeros((5, 5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [17]:
#eye
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [18]:
#2D array
a = np.array([[1, 2, 3], [4, 5, 6]])
print(a.ndim)

2


In [19]:
a.dtype

dtype('int32')

In [20]:
ar = np.array([1, 2, 3, 4, 5, 6], ndmin = 5)
ar

array([[[[[1, 2, 3, 4, 5, 6]]]]])

In [21]:
ar.ndim

5

In [22]:
#linspace
np.linspace(0, 10, 3)

array([ 0.,  5., 10.])

In [23]:
np.linspace(0, 10, 50)

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

In [24]:
a = np.arange(25)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24])

In [25]:
a.max()

24

In [26]:
a.min()

0

In [27]:
a.argmax() #indexposition

24

In [28]:
a.argmin()

0

In [29]:
#operations
a = np.array([1, 2, 3, 4, 5])
b = np.array([10, 20, 30, 40, 50])
print(a + b)

[11 22 33 44 55]


In [30]:
a - b

array([ -9, -18, -27, -36, -45])

In [31]:
a * b

array([ 10,  40,  90, 160, 250])

In [32]:
a / b

array([0.1, 0.1, 0.1, 0.1, 0.1])

In [33]:
a = np.array([[1, 2, 3], [4, 5, 6]])
b = np.array([[7, 8, 9], [10, 11, 12]])
np.add(a, b)

array([[ 8, 10, 12],
       [14, 16, 18]])

In [34]:
np.subtract(a, b)

array([[-6, -6, -6],
       [-6, -6, -6]])

In [35]:
np.multiply(a, b)

array([[ 7, 16, 27],
       [40, 55, 72]])

In [36]:
np.divide(a, b)

array([[0.14285714, 0.25      , 0.33333333],
       [0.4       , 0.45454545, 0.5       ]])

In [37]:
a = np.array([[1, 2], [4, 5]])
b = np.array([[7, 8], [10, 11]])

In [38]:
np.dot(a, b)

array([[27, 30],
       [78, 87]])

In [39]:
np.sqrt([[1, 2],[4, 5]])

array([[1.        , 1.41421356],
       [2.        , 2.23606798]])

In [40]:
np.exp([[1, 2], [3, 4]])

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [41]:
np.sin([[1, -2], [-3, 4]])

array([[ 0.84147098, -0.90929743],
       [-0.14112001, -0.7568025 ]])

In [42]:
np.log([[1, 2, 3], [4, 5, 6]])

array([[0.        , 0.69314718, 1.09861229],
       [1.38629436, 1.60943791, 1.79175947]])

In [43]:
#INDEXING 
a = np.array([[1, 2, 3], [4, 5, 6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [44]:
print(a[0][0])

1


In [45]:
a[0][0]

1

In [46]:
a[1:, 1:]

array([[5, 6]])

In [47]:
a[0:,1:]

array([[2, 3],
       [5, 6]])

In [48]:
a[:, 1:]

array([[2, 3],
       [5, 6]])

In [49]:
#broadcasting
a = np.arange(0, 11)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [50]:
a[5:]

array([ 5,  6,  7,  8,  9, 10])

In [51]:
a[:5]

array([0, 1, 2, 3, 4])

In [52]:
a[0:5] = 100
a

array([100, 100, 100, 100, 100,   5,   6,   7,   8,   9,  10])

In [53]:
a[:] = 100
a

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [54]:
b = a.copy()
b

array([100, 100, 100, 100, 100, 100, 100, 100, 100, 100, 100])

In [55]:
#where
a = np.array([1, 2, 3, 4, 5, 4, 6, 4, 7, 4])
res = np.where(a==4)
res

(array([3, 5, 7, 9], dtype=int64),)

In [56]:
#selection
data = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
data

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [57]:
data[(data >= 5) & (data <= 8)]

array([5, 6, 7, 8])

In [58]:
np.random.rand(2) #(0, 1 between values)

array([0.78196471, 0.43030309])

In [59]:
np.random.rand(5, 5)

array([[0.49999641, 0.91770892, 0.04395401, 0.65131906, 0.42252309],
       [0.6633552 , 0.72424574, 0.7684753 , 0.02707286, 0.22460234],
       [0.40496347, 0.99260667, 0.21257065, 0.13982383, 0.9662159 ],
       [0.57289057, 0.30150484, 0.72877359, 0.00116109, 0.24992633],
       [0.32161921, 0.15490439, 0.26080189, 0.80982261, 0.62784579]])

In [60]:
np.random.randn(5, 5)  # mean = 0,std = 1

array([[ 1.39822482,  1.04099274,  0.6051565 , -0.88488343,  2.13973706],
       [-0.4192734 , -0.69512367, -0.303282  ,  1.62228058, -2.12861892],
       [ 1.03926839, -0.0441114 ,  0.61151862, -0.09724989,  0.07176094],
       [ 0.10101145,  1.14855027,  0.69101341, -0.00728903, -0.17681774],
       [-0.6871769 , -0.15896161, -0.05798788,  0.09691593,  1.84409626]])